---
- hosts: localhost
  connection: local

  tasks:

    - name: Atualizando servidor
      apt: 
        update_cache: yes
      become: true

    - name: Instalando Docker
      shell: curl -fsSL https://get.docker.com | bash
      args:
        warn: no
      become: true

    - name: Instalando Docker-Docker-Compose
      apt:
        name: docker-compose
        state: present
      become: true

    - name: Iniciando Zabbix-Docker
      docker_compose:
        project_src: "{{ playbook_dir }}"
        files:
        - "docker-compose.yaml"
        state: present
      become: true